### ISSUE TITLE
add this image full screen to the value of values slide

### ISSUE THREAD

**Issue by webappzero** [webappzero/cr17-to-zero#101]
And also create a slide under close with this, which we will follow up with slide on our discussion site. Maybe you can come up with a screen shot of our discourse site for that too?

https://pixabay.com/en/milky-way-andromeda-stars-galaxy-923801/

**Comment by whilei** [comment]
Got it! See #100, commit d0fc0e7. 

PR includes redpill `(FRAG)` notes and the above ticket. 🛠 

💯 Happy to merge myself and let you just pull if you want... depending on where your own writing/branch is at. Just let me know.
