### ISSUE TITLE
next note should be scrolled to top of text

### ISSUE THREAD

**Issue by webappzero** [webappzero/cr17-to-zero#32]
Presently, I'm using a very small speaker notes window (by pressing `t`) to keep the text over my web cam.

I scroll the text down to the bottom as I read it, and then hit `n` key for next slide. 

The notes for the next slide, if they are long, will already be scrolled near their bottom. In fact, I think the window retains its scroll position instead of resetting to the top.

The good news is that I can get by perfectly with just the text window, so please desist all other work on the speaker note variations. I don't have to keep my laptop lid half-closed as I assumed I would. This means I can look down and see the present slide, if needed. 

Can we reset each new slide's notes to the top? Does that make sense?

Good example is going from slide titled "5 Days" to the next slide.

Notice I've put a vertical set of dots in most notes. These are intentional. Please leave them in place.

**Comment by webappzero** [comment]
Behavior is unchanged on my end. Here's a minute long video showing issue:

https://youtu.be/OTWaelrjBhc

**Comment by whilei** [comment]
Got it. WIP.
