### ISSUE TITLE
Big red pill + QR inside? 

### ISSUE THREAD

**Issue by whilei** [webappzero/cr17-to-zero#42]
Check out branch `big-redpill` to compare.

Sneak peek!
![screen shot 2017-02-01 at 15 39 47](https://cloud.githubusercontent.com/assets/10228550/22511081/baa7b442-e894-11e6-874a-512c176e811e.png)

**Comment by webappzero** [comment]
I think I prefer this because it's easy to talk about. I can say scan the red pill and its obvious what I mean.

How well does the qr code scan for you?

**Comment by whilei** [comment]
Reopening because I couldn't get QRs for polling (#34) to scan inside the red pill, but they're working for me in standalone format.

**Comment by whilei** [comment]
And we may be presented with the challenge of multiple QRs, depending on our polling approach.

**Comment by webappzero** [comment]
Can we try using white of grey for the border around the QR code, but still
inside the red pill?

**Comment by whilei** [comment]
White works a lot better! Let's go with that.
