### ISSUE TITLE
Full size video?

### ISSUE THREAD

**Issue by whilei** [webappzero/cr17-to-zero#46]
Setting should be variable per slide.

**Comment by whilei** [comment]
Check out branch `big-video` for a sample, where I put the example full-size video on slide `Two faces of education` 😏  just for a test run. 

Notice that the slides before and after use `PROPERTIES video-size="normal"` to _unset_ the video fullsizing. There is probably a more elegant solution but may not be worth the time to chase down if this works for you.

**Comment by webappzero** [comment]
This sounds like it will work fine. Thank you Isaac!

**Comment by whilei** [comment]
Cool! Wherever you'd like to use fullsize, just let me know with a `TODO` marker, etc.
