### ISSUE TITLE
markdown syntax visible on 2 slides 

### ISSUE THREAD

**Issue by webappzero** [webappzero/cr17-to-zero#61]
Formatting is off on these 2 slides for me. 

http://img.webappzero.com/j2bP

http://img.webappzero.com/j2Rg

Thank you Isaac! You're rockin' it!!!

**Comment by whilei** [comment]
❔ I'm getting black images...

Downloading yields:
![screenshot 2017-02-04 09 59 37 3](https://cloud.githubusercontent.com/assets/10228550/22619682/4e4a1796-eafa-11e6-9156-303f22f2f6ad.png)

Maybe just try dropping the screenshots right in this issue?

**Comment by webappzero** [comment]
Doh!

Here we go:

http://img.webappzero.com/j2A5

http://img.webappzero.com/j2RI

**Comment by whilei** [comment]
Indeed! I used a markdown-src code block there, with the thought that the "raw source" idea might play well with the idea of a dictionary. But, on the other hand, I can definitely see that markdown punctuation might be distracting.

Pull request #62 changes the definitions to use org-mode table format (which is great, by the way!)

As the PR mentions, there are still some annoying borders cropping up in the tables but I don't expect that to be too tricky to iron out.
