### ISSUE TITLE
can't find http://www.whatisquantumplation.org ?

### ISSUE THREAD

**Issue by whilei** [webappzero/cr17-to-zero#71]

**Comment by webappzero** [comment]
oops, I forgot it's actually .com

http://whatisquantumplation.com/

**Comment by whilei** [comment]
It's beautiful.

**Comment by whilei** [comment]
And hilarious.

**Comment by webappzero** [comment]
Yes it's very I heart Huckabee's movie-like.

**Comment by webappzero** [comment]
I think I'll save revealing this a more light-hearted moment. Don't want to water down my first talk with made up words. : )
