### ISSUE TITLE
How to label blank bullets

### ISSUE THREAD

**Issue by webappzero** [webappzero/cr17-to-zero#75]
FYI, if you need to create a title with a blank header, you can label that header in a way that is visible even when the outline mode is fully collapsed by placing `:noexport:` at the end a header (we can call this a label header) of equal status (H1 etc) just before the blank header.

Here's an example screenshot:
http://img.webappzero.com/j1q5

Source reference: http://emacs.stackexchange.com/questions/7597/comment-lines-in-org-mode-with-clean-view

**Comment by whilei** [comment]
Your `* _ Header  :noexport` style is noted and I like it a lot. Will use.
