### ISSUE TITLE
full screen request

### ISSUE THREAD

**Issue by webappzero** [webappzero/cr17-to-zero#77]
see http://img.webappzero.com/j1qX

**Comment by whilei** [comment]
~~I say "partially" because until the slide gets a spot in the talk it doesn't make sense yet to implement the necessary "bookmarks" to ensure video size returns to normal for the adjacent slides.~~

Found the other one 😜

**Comment by webappzero** [comment]
I should've pointed out I'm keeping copies of some sections in the notes section of the talk which creates duplicate names for some headings when searching. Looks like you figured this out on your own. : )
