### ISSUE TITLE
Speaker Notes Teleprompter

### ISSUE THREAD

**Issue by webappzero** [webappzero/cr17-to-zero#8]
This is a total stretch goal, after everything else is done, but it would be cool to have a reveal.js plugin that would allow the repositioning and sizing of the speaker notes text div within the speaker window. And also the ability to control the speed and delay of scrolling text using something like: http://richhollis.github.io/vticker.

In my present case I have 3 displays, the macbookpro display, an asus and an lg, from bottom to top.

There's a setting in macos System Preferences | Mission Control | Displays have seperate Spaces

When this toggle is unchecked, you are able to place a window between two displays, with part of the window shown on each display. This will allow me to size and position the Presenter Notes Chrome Window such that the presenter notes are in the right position for my webcam, and the remaining contents of the window spread across 2 displays (not ideal but it works). I'm using a teleprompter which fits over the webcam. This makes the scrolling feature the priority of the two features mentioned in this issue. Whew!

**Comment by webappzero** [comment]
I'm amazed at our progress on the design of the presentation. I'm thinking this stretch goal might be the smartest thing to start working on in between making things look great.

I've been thinking about the simplest way to do this. Because I can mirror the presentation between my laptop screen and top screen, I would be able to see the current slide by looking up. Although, I'll be mainly focussed on reading the text.  This means we could eliminate both the current slide and preview slide from the notes window. Also, I don't the timer bar within the notes as I'll have a screenflow timer.

Being able to size the window of the the notes to the size of my teleprompter, without concern for the now deleted other components, slide and next slide will be a big win. Version 1 won't need an auto-scroll jquery component. I can manually scroll to get some idea of what that is like.

We can then talk about the cost benefit of adding auto-scroll. So task one is to remove the divs with ids: `current-slide` & `upcoming-slide`

**Comment by webappzero** [comment]
If it looks easy to do, it would be nice to have the current and next slide in a separate window. This would allow me to use that on my 3rd display, instead of mirroring.

**Comment by webappzero** [comment]
The other option to separate windows, if that doesn't work. Is to place the notes in between the other two panes and make its size adjustable.

**Comment by webappzero** [comment]
Please leave the timer element in. I need a buffer of space there. Let's pin it there please.

**Comment by whilei** [comment]
It looks like it may be a little tricky getting simultaneous and separate text/+preview windows. With regard to positioning the notes between panes -- what do you think about this layout? 

![screen shot 2017-01-30 at 16 56 08](https://cloud.githubusercontent.com/assets/10228550/22430066/279defbe-e70d-11e6-9623-21162e57c826.png)

I pushed it to branch `speaker-controls`, and it's accessible by hitting the standard `s`, if you'd like to take it for a spin. 

```shell
git fetch upstream # or 'origin', wherever you call this place ;-)
git checkout upstream/speaker-controls
# take her around the block... then:
git checkout master # and you're back to normal
```

If you'd like to go with a resizable notes window, that is definitely possible too!

**Comment by webappzero** [comment]
Great progress! Let's try stacking the current slide above the upcoming slide on the left, and having the speakers notes on the right, in an adjustable sized pane, if possible. My webcam sits at the top of my monitor, where the teleprompter will be. The tele-prompter uses a mirror to extend down from my webcam over the display, hence I need the notes to near the top of the screen. Maybe we could put the timer back in above the notes to act as a space buffer because I don't want the notes to be ALL the way at the top. The timer should be pinned there so the notes can be scrolled without displacing the timer.

**Comment by webappzero** [comment]
The timer isn't a priority now that I think about it, because I can just lower the entire window if I need a buffer. Just in case that is trickier than it seems.

**Comment by whilei** [comment]
Closing in lieu of #32
