### ISSUE TITLE
write red pill doc

### ISSUE THREAD

**Issue by webappzero** [webappzero/cr17-to-zero#82]
Please write up a lean, rough draft of instructions on how to construct red pill with qr code link to a website.

A brief screencast video recording showing an entire walkthrough of yourself going through the steps would also be nice, but isn't necessary if the required workflow to produce said screenflow is too onerous, in light of other priorities. I believe Quicktime and builtin mic are a good starting point for tools.

**Comment by whilei** [comment]
💊  https://github.com/webappzero/the-value-of-learning/wiki/How-to-use-the-redpills

Video to follow...

**Comment by whilei** [comment]
Video ~~uploading currently~~ __good to go!__ Available at https://youtu.be/TnvRApdG3gw
