### ISSUE TITLE
video?

### ISSUE THREAD

**Issue by webappzero** [webappzero/cr17-to-zero#87]
How hard would it be to insert a video to play at fullscreen, or normal, at certain times, instead of my live feed?

**Comment by whilei** [comment]
I think it can be done. What do you have in mind?

**Comment by webappzero** [comment]
I was thinking of playing a brief video clip of prerecorded video (.mp4) in one or two spots, not exactly sure yet where. Could you try working with any ol' file you have laying around?

**Comment by webappzero** [comment]
I think now that we're down to the last couple days, it's best to close this until after the talk. 

Instead I think we should focus on our audience interaction. Polls etc.

**Comment by whilei** [comment]
Aha! Glad to hear it. I'm actually just pushing up a limited implementation on branch `video-src` to my remote currently. Will move on.
