### ISSUE TITLE
restore clock timer to speaker notes

### ISSUE THREAD

**Issue by webappzero** [webappzero/cr17-to-zero#88]
Isaac, how big of a deal would it be to restore the clock timer to the speaker notes?

I want to follow your advice and do less of a scipted talk and speak more naturally. Thing is, to do that I'll have to create time milestones so I know when to wrap up and move on. I can use another app for this but if its not much work and you have time, then go for it.

**Comment by whilei** [comment]
Should be very straightforward. 💅

**Comment by whilei** [comment]
What if they were fixed to float on top, so your notes scroll underneath them? Would that help?

Otherwise you'll lose view of the timer as you scroll down.
