### ISSUE TITLE
video killed the radio star

### ISSUE THREAD

**Issue by webappzero** [webappzero/cr17-to-zero#93]
Embedded video on reveal.js presentation lags unacceptably on crowdcast.

Also on Google Hangouts.

Not on Skype! Yay!

Zoom is decent, but not ideal.

My gut says the issue is webrtc. I know hangouts uses, and I suspect crowdcast does because they don't support safari. http://caniuse.com/#search=webrtc

I suppose we could always send people a link to a Skype webinar. I'll check with Ryan, but this isn't a graceful solution for conference attendees. Hey, we want to move the conference to Skype because some video will be missing otherwise. Most people will likely say, we can live without it.

**Comment by whilei** [comment]
See new branch [`no-vid`](https://github.com/webappzero/the-value-of-learning/tree/no-vid). For now, I'll leave it as it's own branch instead of a PR; that way we can jump back and forth as long as we mind the rebasers.

**Comment by whilei** [comment]
🖇 Of note – and obviously, but wanted to get it documented here – we'll need to 🔪 out the fullscreen videos... __OR(?)__ leave them in as ques for when you want to ask Ryan to go fullscreen via the CC interface.
