### ISSUE TITLE
blue pill to right middle

### ISSUE THREAD

**Issue by webappzero** [webappzero/cr17-to-zero#94]
Let's leave the top right third free for pasting in the video in post production.

Hence, blue pill goes to middle instead of all the way at the top as previously discussed.

**Comment by whilei** [comment]
![screen shot 2017-02-09 at 09 35 13](https://cloud.githubusercontent.com/assets/10228550/22775254/16dff4f6-eeab-11e6-9071-d95f4526fe93.png)

📌  Looking good?

**Comment by webappzero** [comment]
let' move it down.

How about we divide the right third of screen, (where the pill is now) up into 3 vertically stacked thirds, and center the pill in the resulting box. Each Blue pill in the box above that. All blue pill link to the same page: http://www.theverylastpageontheinternet.com/, but they have no link icon to entice such needless wanderings.

Thank you Isaac!

**Comment by webappzero** [comment]
No, never mind about linking the bluepills now. don't sweat that detail. just blank blue pill, let me get you a color code for that.

**Comment by webappzero** [comment]
Doh! We have a blue color. Please just use our blue  from title page : )

**Comment by whilei** [comment]
👓 
![screen shot 2017-02-09 at 12 20 15](https://cloud.githubusercontent.com/assets/10228550/22781289/254e5462-eec2-11e6-9593-a062c8ef4ccd.png)

Bluepills work just like redpills as far as calling in from org-mode, except only they're `bluepill-img-src` and `bluepill-qr-data`. 
QR's still optional all around.

**Comment by webappzero** [comment]
Perfect.

**Comment by webappzero** [comment]
Let's skip the QR code on blue. Just pill.

**Comment by whilei** [comment]
Do you want blue pills on _every_ slide? 

> [...] Each Blue pill in the box above that. All blue pill link to the ...

**Comment by webappzero** [comment]
Every slide where a red pill is found. This implies choice, which I'm a fan of, even though Isaac Einstein himself didn't believe in free will. We should (IMHO), for the sake of humanity, carry on as though we do have, regardless of reality.

**Comment by whilei** [comment]
Gotcha -- but no QR links on any of the bluepills? (--Limits the choice a little, eh?)

**Comment by webappzero** [comment]
The choice, as morpheus states is to remain as you are, and believe whatever you _**want**_ to believe.

The blue pill is a no-op.

Okay, you've changed my mind. Put the same QR code on each blue pill, which points to http://www.theverylastpageontheinternet.com/

Nice one messy brain!
