### ISSUE TITLE
increase font sizes

### ISSUE THREAD

**Issue by webappzero** [webappzero/cr17-to-zero#95]
Got some feeback on font sizes. Let's try doubling everything, not that we have more room.

Of course, if it doesn't look right to you, scale down until it does. Gotta trust my right brain ; )

**Comment by whilei** [comment]
😁 
just came to post this up and see whatcha thought...
> tolitius [5:33 AM] 
> @jay if still possible (given how much is already planned) I would suggest to increase the font size during the talk

Will hit it quick 🔨

**Comment by whilei** [comment]
Branch `bigger-font` increases the default sizes all around, and is based off of branch `no-vid`, so it includes those changes too.

https://github.com/webappzero/the-value-of-learning/tree/bigger-font
